server.port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dineshvenba0811/PvtOrganisation-microservice-config
          default-label: main
  #profiles:
   # active: docker